// Reference QR matrix generator for the golden tests in tests/qr.
//
// It uses macOS CoreImage (CIQRCodeGenerator), an implementation written by
// someone else, so the encoder in nro/source/ui/qr.c is verified against an
// independent implementation instead of against itself.
//
// Build and run on macOS:
//
//   clang -fobjc-arc -framework Foundation -framework CoreImage \
//       -framework CoreGraphics tests/qr/tools/gen_reference.m -o /tmp/gen_reference
//   /tmp/gen_reference "HELLO" M > tests/qr/golden/hello_m.txt
//
// CoreImage returns the symbol with a one module light border, which is the
// quiet zone; the NRO draws its own quiet zone, so the border is stripped here.

#import <CoreGraphics/CoreGraphics.h>
#import <CoreImage/CoreImage.h>
#import <Foundation/Foundation.h>

int main(int argc, const char** argv)
{
    @autoreleasepool {
        if (argc < 3) {
            fprintf(stderr, "usage: gen_reference <text> <L|M|Q|H>\n");
            return 2;
        }

        NSString* text = [NSString stringWithUTF8String:argv[1]];
        NSString* level = [NSString stringWithUTF8String:argv[2]];
        NSData* data = [text dataUsingEncoding:NSUTF8StringEncoding];

        CIFilter* filter = [CIFilter filterWithName:@"CIQRCodeGenerator"];

        if (filter == nil) {
            fprintf(stderr, "CIQRCodeGenerator is unavailable\n");
            return 3;
        }

        [filter setValue:data forKey:@"inputMessage"];
        [filter setValue:level forKey:@"inputCorrectionLevel"];

        CIImage* output = filter.outputImage;

        if (output == nil) {
            fprintf(stderr, "no output image\n");
            return 4;
        }

        CIContext* context = [CIContext context];
        CGImageRef image = [context createCGImage:output fromRect:output.extent];

        if (image == NULL) {
            fprintf(stderr, "could not rasterise the symbol\n");
            return 5;
        }

        size_t width = CGImageGetWidth(image);
        size_t height = CGImageGetHeight(image);
        unsigned char* pixels = calloc(width * height, 1);
        CGColorSpaceRef space = CGColorSpaceCreateDeviceGray();
        CGContextRef bitmap = CGBitmapContextCreate(pixels, width, height, 8, width, space,
            (CGBitmapInfo)kCGImageAlphaNone);

        CGContextDrawImage(bitmap, CGRectMake(0, 0, width, height), image);

        // CoreImage draws the symbol with its own one module quiet zone.
        size_t size = width - 2;
        size_t margin = 1;

        if (width != height || size < 21) {
            fprintf(stderr, "unexpected symbol size %zux%zu\n", width, height);
            return 6;
        }

        printf("# generated by tests/qr/tools/gen_reference.m (macOS CoreImage CIQRCodeGenerator)\n");
        printf("# text: %s\n", argv[1]);
        printf("# level: %s\n", argv[2]);
        printf("# size: %zu\n", size);

        // The first rows in a CGBitmapContext already hold the top of the
        // symbol: checked with the finder patterns and the dark module, see the
        // orientation note in this tool's history.
        for (size_t row = 0; row < size; row++) {
            size_t y = margin + row;

            for (size_t col = 0; col < size; col++)
                putchar(pixels[y * width + margin + col] < 128 ? '1' : '0');

            putchar('\n');
        }

        CGContextRelease(bitmap);
        CGColorSpaceRelease(space);
        CGImageRelease(image);
        free(pixels);
    }

    return 0;
}
